---
deployment:
  tasks:
    - export DEPLOYPATH=/home/repositories/jaswill-backend
    - mkdir -p $DEPLOYPATH

    - export PUBLISHFOLDER=bin/Release/net6.0/publish
    - dotnet publish -c Release -o $DEPLOYPATH/$PUBLISHFOLDER

    - cp -r * $DEPLOYPATH
    - cd $DEPLOYPATH
    - rm -rf $PUBLISHFOLDER

    - mkdir -p CMS_appBackend
    - touch CMS_appBackend/restart

options:
  build_dir: ""
