services:
  - name: jaswillbackend
    buildCommand: "npm install && npm run build"
    startCommand: "node out/server.js"
    env:
      - key: MYSQL_HOST
        fromDatabase:
          name: JaswillRealEstate
          property: localhost
      - key: MYSQL_PORT
        fromDatabase:
          name: JaswillRealEstate
          property: 3306
      - key: MYSQL_DATABASE
        fromDatabase:
          name: JaswillRealEstate
          property: jaswillbackend
      - key: MYSQL_USER
        fromDatabase:
          name: JaswillRealEstate
          property: root
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: JaswillRealEstate
          property: html12345
