version: '3'
services:
  jaswillbackend:
    container_name: jaswillbackend.test
    image: jaswillbackend:${WEBAPP_VERSION}
    build:
      context: ../
      dockerfile: ./Docker/App.dockerfile
      args:
        WEBAPP_VERSION: ${WEBAPP_VERSION}
        URL_PORT: ${URL_PORT}
    ports:
      - "5000:${URL_PORT}"
    volumes:
      - jaswillbackendbuild:/app
    depends_on:
      - builder
  
  builder:
    container_name: latest
    image: jaswillbackend:${BUILDER_VERSION}.${BUILD_CONFIG}
    build:
      context: ../
      dockerfile: ./Docker/App.dockerfile
      args:
        BUILDER_VERSION: ${BUILDER_VERSION}
        BUILD_CONFIG: ${BUILD_CONFIG}
        BUILD_LOCATION: ${BUILD_LOCATION}
    volumes:
      - jaswillbackendbuild:${BUILD_LOCATION}

volumes:
  jaswillbackendbuild: